[project]
name = "dataforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kafka-python>=2.2.15",
    "pandas>=2.3.2",
    "psycopg2>=2.9.10",
    "pulsar-client>=3.8.0",
    "pytest>=8.4.1",
]
